SELECT T.TEAM_ID "TeamId",
       T.NAME "Name",
       T.DESCRIPTION "Description",
       L.COUNTRY "Country",
       T.FOUNDATION_DATE "FoundationDate",
       SUM(P.TRANSFER_COST) "Totalcost"
    FROM SYSTEM.TEAM T
    LEFT JOIN LEAGUE L ON T.LEAGUE_ID = L.LEAGUE_ID
    LEFT JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
    LEFT JOIN PLAYER_TEAMS_HISTORY PTH ON T.TEAM_ID = PTH.TEAM_ID AND P.PLAYER_ID = PTH.PLAYER_ID AND PTH.ROW_EXP_DT IS NULL
    GROUP BY T.NAME, T.DESCRIPTION, L.COUNTRY, T.FOUNDATION_DATE, T.TEAM_ID